package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"math/rand"
	"net/http"
	"os"
	"os/exec"
	"time"

	"github.com/higgyhiggy/project-0/file"
)

var name bool
var Cmdout string

type autoGenerated []struct {
	Text   string `json:"text"`
	Author string `json:"author"`
}

func init() {
	word := autoGenerated{}

	flag.BoolVar(&name, "file", false, "file name to open or create")
	flag.Parse()
	fmt.Println(len(os.Args))
	rand.Seed(time.Now().UnixNano())
	resp, err := http.Get("https://type.fit/api/quotes")
	if err != nil {
		panic(err)
	}
	defer resp.Body.Close()

	err = json.NewDecoder(resp.Body).Decode(&word)
	if err != nil {
		panic(err)
	}
	txtname := file.Create(name)
	f, _ := os.Create(txtname)
	defer f.Close()
	n2, _ := f.WriteString(word[rand.Intn(len(word))].Text + "\n" + "\n")
	if n2 == 0 {

	}
	out, _ := exec.Command("code", txtname).Output()
	if out != nil {

	}
	Cmdout = "the file created is " + txtname
}
